- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    personal: "{{ lookup('env', 'HOME') }}/Code"
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/brave.yml
    - include: tasks/fzf.yml
    - include: tasks/zsh.yml
    - include: tasks/rbenv.yml
    - include: tasks/dotfiles.yml
    - include: tasks/personal-projects.yml
    - include: tasks/nvim.yml
    - include: tasks/sqlite.yml
    - include: tasks/ruby.yml
