- name: Installing stow
  become: true
  apt:
    name: "stow"
  tags:
    - dotfiles
- name: Cloning .dotfiles
  git:
    repo: 'git@github.com:interludedesign/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    version: main
  tags:
    - dotfiles
- name: Cloning .dotfiles personal
  git:
    repo: 'git@github.com:interludedesign/personal.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles/personal"
    version: main
- name: Cloning .dotfiles work
  git:
    repo: 'git@github.com:interludedesign/work.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles/work"
    version: main
  tags:
    - dotfiles
- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && make personal
  tags:
    - dotfiles
