- name: Download fzf
  git:
    repo: 'https://github.com/junegunn/fzf.git'
    dest: "{{ lookup('env', 'HOME') }}/.fzf"
    version: master
  tags:
    - fzf

- name: Install fzf
  shell: ~/.fzf/install --no-bash --no-fish --no-update-rc --key-bindings --completion
  tags:
    - fzf
