- name: Setup Neovim
  tags: nvim
  block:
    - name: Check if nvim is installed
      command: "which nvim"
      register: nvim_installed
      changed_when: false
      failed_when: false

    - name: Get Packer
      ansible.builtin.git:
        repo: 'https://github.com/wbthomason/packer.nvim'
        dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"

    - name: Install neovim build dependencies
      become: true
      apt:
        pkg:
          - ninja-build
          - gettext
          - libtool
          - libtool-bin
          - autoconf
          - automake
          - cmake
          - g++
          - pkg-config
          - unzip
          - curl
          - doxygen

    - name: Clone neovim
      git:
        repo: 'https://github.com/neovim/neovim.git'
        version: "stable"
        dest: "{{ lookup('env', 'HOME') }}/neovim"
      when: nvim_installed.rc == 1

    - name: Build neovim
      shell: "cd {{ lookup('env', 'HOME') }}/neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo"
      when: nvim_installed.rc == 1

    - name: Install neovim
      become: true
      shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
      when: nvim_installed.rc == 1
