- name: Add an Apt signing key
  become: true
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  tags:
    - postgres

- name: Add to apt sources
  become: true
  ansible.builtin.apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt kinetic-pgdg main
    state: present
  tags:
    - postgres

- name: "Install packages"
  become: true
  apt:
    name: postgresql-15
  tags:
    - postgres
