- name: Install PostgreSQL
  become: yes
  tags: postgres
  block:
    - name: Add PostgreSQL Apt Key
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: Add PostgreSQL Repository
      apt_repository:
        repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main {{ ansible_distribution_release }}
        state: present

    - name: Update APT Cache
      apt:
        update_cache: yes

    - name: Install PostgreSQL and Related Packages
      apt:
        name:
          - postgresql-14
          - postgresql-contrib
          - libpq-dev
        state: present
