- name: Setup Rust
  tags: rust
  block:
    - name: Check if Rust is installed
      command: "which rustc"
      register: rust_installed
      changed_when: false
      failed_when: false

    - name: Download Installer
      when: rust_installed.rc != 0
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: '0755'
        force: 'yes'

    - name: Install rust/cargo
      when: rust_installed.rc != 0
      shell: /tmp/sh.rustup.rs -y
