- name: Install powerlevel10k
  git:
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    dest: "{{ lookup('env', 'HOME') }}/.powerlevel10k"
    version: master
  tags:
    - zsh
    - 10k
- name: Install ZSH
  become: true
  apt: name=zsh
  tags:
    - zsh
- name: Change shell to zsh
  become: true
  shell: chsh -s $(which zsh)
  tags:
    - zsh
